#Horizontal range
# Default: 4
# Range: 1 ~ 9
horizontalRange = 4
#Vertical range
# Default: 1
# Range: 0 ~ 4
verticalRange = 1
#Tics in between Crop Dusting
# Default: 20
# Range: 10 ~ 200
everyTics = 20
#1 in 'x' chances the player will spawn particles and fart (Depends on the other settings been set to true)
# Default: 10
# Range: 2 ~ 100
chancesPool = 10
#Spawn some particles behind player simulating farts
doParticles = true
#Play fart sounds at random
playFartSounds = true
